name: 🚀 CI Backend Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Checkout du code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install

      - name: Corriger les permissions Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: Lancer les tests Jest
        run: npm test
